// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcetiarxtlzvvcvjtmqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZXRpYXJ4dGx6dnZjdmp0bXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzU5ODIsImV4cCI6MjA2NjYxMTk4Mn0.6Upz_jE3WjCU2LCmYuvX-_vchhWiEgcm1WBXYUpXUf4";

// Validate environment
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase configuration');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase: ReturnType<typeof createClient<Database>>;

try {
  console.log('Initializing Supabase client...');
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  console.log('Supabase client initialized successfully');
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  throw error;
}

export { supabase };
