// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcetiarxtlzvvcvjtmqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZXRpYXJ4dGx6dnZjdmp0bXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzU5ODIsImV4cCI6MjA2NjYxMTk4Mn0.6Upz_jE3WjCU2LCmYuvX-_vchhWiEgcm1WBXYUpXUf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);